# Generated by Django 5.0.4 on 2024-04-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0004_orderdetail_address_orderdetail_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('Неоплачен', 'Неоплачен'), ('Оплачен', 'Оплачен'), ('Доставляется', 'Доставляется'), ('Доставлен', 'Доставлен')], default='Неоплачен', max_length=100),
        ),
    ]
