# Generated by Django 5.0.4 on 2024-04-25 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0004_alter_product_rating'),
        ('orders_app', '0005_alter_orderdetail_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_app.product')),
            ],
            options={
                'verbose_name': 'Товары в заказе',
                'verbose_name_plural': 'Список товаров по номеру заказа',
            },
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='items',
            field=models.ManyToManyField(to='orders_app.orderitem'),
        ),
        migrations.DeleteModel(
            name='OrderItems',
        ),
    ]
