# Generated by Django 5.0.4 on 2024-04-25 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0006_orderitem_orderdetail_items_delete_orderitems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'verbose_name': 'Заказы', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='items',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='orders_app.orderdetail'),
            preserve_default=False,
        ),
    ]
