# Generated by Django 5.0.4 on 2024-04-25 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0007_alter_orderdetail_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='orders_app.orderdetail'),
        ),
    ]
