# Generated by Django 3.2.12 on 2024-04-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
